### PR TITLE
Correct link to contribution-guidelines repo

### PR DESCRIPTION
**Pull request by jung-thomas**
Incorrect link to contribution-guidelines repo in the dos-and-donts.md

### CODE REVIEW

**Review by qmacro — APPROVED** [review]
LGTM, thanks!

**Comment by jung-thomas** [comment]
https://people.sap.com/thomas.jung

**Comment by marcobuescher** [comment]
https://people.sap.com/marco.buescher

**Comment by qmacro** [comment]
Hi @marcobuescher - can you tell us why you added your SAP Community profile URL to this PR?

**Comment by marcobuescher** [comment]
That was a mistake, I forgot to delete it…sorry…

Von: DJ Adams ***@***.***>
Gesendet: Dienstag, 29. Juni 2021 10:53
An: SAP-docs/contribution-guidelines ***@***.***>
Cc: buescher ***@***.***>; Mention ***@***.***>
Betreff: Re: [SAP-docs/contribution-guidelines] Correct link to contribution-guidelines repo (#40)


Hi @marcobuescher<https://github.com/marcobuescher> - can you tell us why you added your SAP Community profile URL to this PR?

**Pull request merged**
