### PR TITLE
Add info about Enterprise Managed Users

### PR DESCRIPTION
**Pull request by je-hal**
Solves #86.

### CODE REVIEW

**Review by qmacro — APPROVED** [review]
👍

**Comment by je-hal** [comment]
@qmacro: I cannot yet see my contribution on the corresponding [SAP Help Portal page](https://help.sap.com/products/open-documentation-initiative/contribution-guidelines/contributing.html). Could you please check?

**Comment by hal-ey** [comment]
@qmacro: I checked. The publishing step for HTML wasn't done yet. I's done now.

**Comment by je-hal** [comment]
@qmacro: I checked. The publishing step for HTML wasn't done yet. I's done now.

**Pull request merged**
